language: go

go:
- 1.11

sudo: true

os:
- linux
- osx

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install jq && go get -u golang.org/x/lint/golint/... && go get -u golang.org/x/tools/cmd/... ; fi

script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then GO111MODULE=on ./test.sh ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t quay.io/jzelinskie/faq:latest . ; fi

notifications:
  email: false
