language: go

go:
- 1.11

sudo: true

os:
- linux
- osx

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install make jq && go get -u golang.org/x/lint/golint/... && go get -u golang.org/x/tools/cmd/... ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install make ; fi

script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make test ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make docker-build ; fi

notifications:
  email: false
