language: go

sudo: true

os:
- linux
- osx

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install jq && go get -u github.com/golang/dep/... && go get -u github.com/golang/lint/... && go get -u golang.org/x/tools/cmd/... ; fi

script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./test.sh ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t quay.io/jzelinskie/faq:latest . ; fi

notifications:
  email: false
