name: Build & Test
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  tests:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-20.04'
        run: sudo apt-get install -y libjq-dev libonig-dev gcc
      - name: Run tests
        run: make test

  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-20.04'
        run: sudo apt-get install -y libjq-dev libonig-dev gcc
      - name: Build executable
        run: make build

  docker:
    name: Build Docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "::set-output name=ref::$(git status | head -1 | awk '{print $NF}' | sed 's#/#_#g')"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master
      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: |
            quay.io/jzelinskie/faq:${{ steps.vars.outputs.ref }}
      - name: Login to Quay
        uses: docker/login-action@v1
        if: github.event_name == 'push'
        with:
          registry: quay.io
          username: jzelinskie+faq_gha
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Push to Quay
        uses: docker/build-push-action@v2
        if: github.event_name == 'push'
        with:
          push: true
          tags: |
            quay.io/jzelinskie/faq:${{ steps.vars.outputs.ref }}
