name: Lint
on:
  push:
    branches:
    - "master"
  pull_request:
    branches:
    - "*"
jobs:
  tests:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Go Lint
        uses: Jerome1337/golint-action@v1.0.2
